version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80"
